#!/usr/bin/env python3
"""
Makes fake Alpha Vantage fixtures (SPY, EEM, and FX history) in the same format as the real API.

The free demo key doesn't return this data, so these let the comparison work in dev.
Each file is marked "synthetic": true in _manifest.json and the UI shows it as sample data.

To replace them with real data:
    python3 ops/tools/record_alphavantage.py

It never overwrites a recorded file, and the seed is fixed so the output is always the same.
"""

from __future__ import annotations

import json
import math
import random
from datetime import date, timedelta
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "ops" / "fixtures"
MANIFEST = FIXTURE_DIR / "_manifest.json"

START = date(2025, 6, 2)
END = date(2026, 9, 25)  # same date as the spot fixtures

NOTE = ("NOT recorded. Generated by ops/tools/make_synthetic_av_fixtures.py (seeded random "
        "walk) in the real response shape. Record with ops/tools/record_alphavantage.py "
        "before relying on the numbers.")


def business_days(start: date, end: date) -> list[date]:
    days, d = [], start
    while d <= end:
        if d.weekday() < 5:
            days.append(d)
        d += timedelta(days=1)
    return days


def walk(rng: random.Random, n: int, drift: float, vol: float, end_value: float) -> list[float]:
    """
    Random daily prices that end exactly at end_value.
    The total move over the period is fixed by drift, so a bad seed can't make
    a pegged currency swing 20% in a year.
    """
    dt = 1 / 252
    logs, x = [], 0.0
    for _ in range(n):
        x += vol * math.sqrt(dt) * rng.gauss(0, 1)
        logs.append(x)
    target = drift * n * dt
    bridged = [l - (logs[-1] - target) * (i + 1) / n for i, l in enumerate(logs)]
    return [end_value * math.exp(b - bridged[-1]) for b in bridged]


def ohlc(rng: random.Random, closes: list[float], intraday: float) -> list[tuple[float, float, float, float]]:
    out, prev = [], closes[0]
    for c in closes:
        o = prev * (1 + rng.gauss(0, intraday / 3))
        hi = max(o, c) * (1 + abs(rng.gauss(0, intraday / 2)))
        lo = min(o, c) * (1 - abs(rng.gauss(0, intraday / 2)))
        out.append((o, hi, lo, c))
        prev = c
    return out


def equity_fixture(symbol: str, days, bars, volumes) -> dict:
    series = {}
    for d, (o, h, l, c), v in sorted(zip(days, bars, volumes), key=lambda t: t[0], reverse=True):
        series[d.isoformat()] = {
            "1. open": f"{o:.4f}", "2. high": f"{h:.4f}", "3. low": f"{l:.4f}",
            "4. close": f"{c:.4f}", "5. volume": str(v),
        }
    return {
        "Meta Data": {
            "1. Information": "Daily Prices (open, high, low, close) and Volumes",
            "2. Symbol": symbol,
            "3. Last Refreshed": days[-1].isoformat(),
            "4. Output Size": "Full size",
            "5. Time Zone": "US/Eastern",
        },
        "Time Series (Daily)": series,
    }


def fx_daily_fixture(base: str, quote: str, days, bars) -> dict:
    series = {}
    for d, (o, h, l, c) in sorted(zip(days, bars), key=lambda t: t[0], reverse=True):
        series[d.isoformat()] = {
            "1. open": f"{o:.5f}", "2. high": f"{h:.5f}", "3. low": f"{l:.5f}", "4. close": f"{c:.5f}",
        }
    return {
        "Meta Data": {
            "1. Information": "Forex Daily Prices (open, high, low, close)",
            "2. From Symbol": base,
            "3. To Symbol": quote,
            "4. Output Size": "Full size",
            "5. Last Refreshed": f"{days[-1].isoformat()} 21:55:00",
            "6. Time Zone": "UTC",
        },
        "Time Series FX (Daily)": series,
    }


def spot_fixture(base: str, quote: str, names: dict, rate: float) -> dict:
    return {
        "Realtime Currency Exchange Rate": {
            "1. From_Currency Code": base,
            "2. From_Currency Name": names[base],
            "3. To_Currency Code": quote,
            "4. To_Currency Name": names[quote],
            "5. Exchange Rate": f"{rate:.8f}",
            "6. Last Refreshed": f"{END.isoformat()} 21:59:00",
            "7. Time Zone": "UTC",
            "8. Bid Price": f"{rate * 0.99974:.8f}",
            "9. Ask Price": f"{rate * 1.00026:.8f}",
        }
    }


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    rng = random.Random(20260928)
    days = business_days(START, END)
    n = len(days)
    names = {"USD": "United States Dollar", "EUR": "Euro", "MAD": "Moroccan Dirham"}

    # Use the existing spot fixtures as the end values.
    usd_mad = walk(rng, n, drift=-0.03, vol=0.05, end_value=9.1845)
    eur_mad = walk(rng, n, drift=0.01, vol=0.04, end_value=10.7312)
    spy = walk(rng, n, drift=0.12, vol=0.16, end_value=662.40)
    eem = walk(rng, n, drift=0.08, vol=0.18, end_value=51.37)

    files: dict[str, tuple[dict, str]] = {
        "av-daily-SPY": (equity_fixture("SPY", days, ohlc(rng, spy, 0.008),
                                        [int(rng.uniform(45e6, 95e6)) for _ in days]),
                         "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=SPY"),
        "av-daily-EEM": (equity_fixture("EEM", days, ohlc(rng, eem, 0.010),
                                        [int(rng.uniform(18e6, 40e6)) for _ in days]),
                         "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=EEM"),
    }
    for base, quote, closes in [("USD", "MAD", usd_mad), ("EUR", "MAD", eur_mad),
                                ("MAD", "USD", [1 / x for x in usd_mad]),
                                ("MAD", "EUR", [1 / x for x in eur_mad])]:
        files[f"av-fxdaily-{base}-{quote}"] = (
            fx_daily_fixture(base, quote, days, ohlc(rng, closes, 0.002)),
            f"https://www.alphavantage.co/query?function=FX_DAILY&from_symbol={base}&to_symbol={quote}")
    for base, quote, rate in [("MAD", "USD", 1 / 9.1845), ("MAD", "EUR", 1 / 10.7312)]:
        files[f"av-fx-{base}-{quote}"] = (
            spot_fixture(base, quote, names, rate),
            f"https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE"
            f"&from_currency={base}&to_currency={quote}")

    for slug, (body, path) in files.items():
        entry = manifest.get(slug)
        if entry is not None and entry.get("synthetic") is False:
            print(f"skip  {slug}: recorded fixture, not overwriting")
            continue
        (FIXTURE_DIR / f"{slug}.json").write_text(json.dumps(body, indent=2) + "\n")
        manifest[slug] = {"method": "GET", "path": path, "body": None, "recordedAt": None,
                          "source": "alphavantage", "synthetic": True, "note": NOTE}
        print(f"wrote {slug}")

    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
